version: "3.9"

services:
  db:
    restart: always
    image: postgres
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    restart: always
    build: ./backend
    container_name: backend
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    env_file:
       - .env.dev
    depends_on:
      - db
    ports:
      - '0.0.0.0:8000:8000'
  frontend:
    restart: always
    command: npm start
    container_name: frontend
    build:
      context: ./frontend/
    ports:
      - "0.0.0.0:3000:3000"
    stdin_open: true
    depends_on:
      - web