# Generated by Django 4.0.2 on 2022-04-02 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('weight', models.FloatField()),
                ('warranty', models.CharField(max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('socket', models.CharField(max_length=20)),
                ('ram_generation', models.CharField(max_length=10)),
                ('ram_type', models.CharField(max_length=10)),
                ('ram_slots_amount', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PowerUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('weight', models.FloatField()),
                ('warranty', models.CharField(max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('power', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('weight', models.FloatField()),
                ('warranty', models.CharField(max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('supply_type', models.CharField(max_length=10)),
                ('socket', models.CharField(max_length=20)),
                ('cores_amount', models.IntegerField()),
                ('threads_amount', models.IntegerField()),
                ('technological_process', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('weight', models.FloatField()),
                ('warranty', models.CharField(max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('form_factor', models.CharField(max_length=10)),
                ('generation', models.CharField(max_length=10)),
                ('mode', models.CharField(max_length=10)),
                ('frequency', models.CharField(max_length=10)),
                ('latency', models.CharField(max_length=10)),
                ('capacity', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorageDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('weight', models.FloatField()),
                ('warranty', models.CharField(max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('type', models.CharField(max_length=10)),
                ('capacity', models.IntegerField()),
                ('form_factor', models.CharField(max_length=10)),
                ('interface', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('weight', models.FloatField()),
                ('warranty', models.CharField(max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('gpu_frequency', models.IntegerField()),
                ('video_memory_size', models.IntegerField()),
                ('video_memory_generation', models.CharField(max_length=10)),
                ('video_memory_frequency', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('weight', models.FloatField()),
                ('warranty', models.CharField(max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('motherboard', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.motherboard')),
                ('power_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.powerunit')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.processor')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.ram')),
                ('storage_device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.storagedevice')),
                ('video_card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.videocard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
