# Generated by Django 4.0.2 on 2022-04-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ram',
            name='mode',
            field=models.CharField(max_length=30),
        ),
    ]
